# Generated by Django 3.1.2 on 2020-10-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
