# Generated by Django 3.1.2 on 2020-10-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_auto_20201010_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
