# Generated by Django 3.1.2 on 2020-10-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201009_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='id',
            new_name='movie_id',
        ),
    ]
