# Generated by Django 3.1.2 on 2020-10-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201009_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(),
        ),
    ]
