# Generated by Django 3.1.2 on 2020-10-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201009_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre_ids',
        ),
    ]
