# Generated by Django 3.1.2 on 2020-10-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20201009_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
