# Generated by Django 3.1.2 on 2020-10-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20201010_0606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
